### PR TITLE
List command: print file immediatly after it is processed

### PR DESCRIPTION
**Pull request by sigmaSd**
fix https://github.com/ouch-org/ouch/issues/212

If performance is a concern , I can make the listing happen in another thread, and each file processed is sent to a shared queue, the printing just pops from the queue each time something is available. This makes the listing not wait for printing to Stdout. But I thought it may not matter that much.

### CODE REVIEW

**Comment by sigmaSd** [comment]
Regarding the last commit, I glanced the code of tar-rs, and adding `into_entries` doesn't look feasible without major rewrite. I think leaking is not that bad though.

**Comment by Crypto-Spartan** [comment]
After reading the documentation for [Box::leak()](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak), is this really the best way to do this? Per the docs:

"This function is mainly useful for data that lives for the remainder of the program’s life. Dropping the returned reference will cause a memory leak. If this is not acceptable, the reference should first be wrapped with the Box::from_raw function producing a Box. This Box can then be dropped which will properly destroy T and release the allocated memory."

At the very least, wouldn't it be best to safely drop the leaked box by first wrapping it in Box::from_raw? 

I feel like Box::leak should be avoided here if possibe as leaking memory goes against the Rust paradigm...

**Comment by sigmaSd** [comment]
The last commit uses a new thread for listing , this gives it best performance since it wont wait for println io , and removes the leak as well.

The only thing I'm not sure about is the "info!(Processing: " line, I think its too verbose, Maybe its better if I made it print on the same line there (with '\r")?

**Comment by marcospb19** [comment]
> The only thing I'm not sure about is the "info!(Processing: " line, I think its too verbose, > Maybe its better if I made it print on the same line there (with '\r")?

Yeah that is too verbose, I think you can just remove it.

If we are going to print something there, probably should just be the name of the archive that will be shown.

**Comment by sigmaSd** [comment]
I changed it to use indicatif, I think it looks good like this, this is similar to what was originally suggested in the issue.

**Comment by marcospb19** [comment]
Looking great!!!!!

**Pull request merged**
