### PR TITLE
Fixes CI artifacts and the manual-release workflow

### PR DESCRIPTION
**Pull request by Flat**

### CODE REVIEW

**Comment by marcospb19** [comment]
I tried using this but it failed, here's [the run result](https://github.com/ouch-org/ouch/actions/runs/7050257974/job/19190539504):

```sh
Run scripts/package-release-assets.sh
  scripts/package-release-assets.sh
  shell: /usr/bin/bash -e {0}
cp: cannot stat 'ouch-aarch64-pc-windows-msvc.exe/artifacts': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by Flat** [comment]
Did you run it based off a build-and-test from this PR? If you use `6998396623` it should work fine. This is due to the changes made to the build-and-test to actually include the manuals and completions as artifacts.

**Review by marcospb19 — APPROVED** [review]
You're such a beast!

Thank you so much for this, and for explaining to me why my test was failing :sweat_smile:.

**Comment by Flat** [comment]
Glad I could help! Hopefully it makes it easier for releases on limited time, haha.

**Pull request merged**
