### PR TITLE
Multi-threaded compression for gzip and snap using gzp

### PR DESCRIPTION
**Pull request by figsoda**
Some benchmark results (compression):

gzip:
about 10 times the speed for a 12M text file
about 13 times the speed for a lot of regular sized files (tar.gz)
about 10% faster for a lot of small files (tar.gz)

snappy:
about 3 times the speed for a 12M text file
about 5 times the speed for a lot of regular sized files (tar.sz)
**about 20% slower for a lot of small files (tar.sz)**

no difference in size of compressed files, +0.2M in binary size in release mode

### CODE REVIEW

**Review by marcospb19 — CHANGES_REQUESTED** [review]
Both seem to be good additions, this should probably go to the changelog.

**Comment by figsoda** [comment]
forgot about that

**Review by marcospb19 — APPROVED** [review]
Looks good, but I'm a little bit afraid of how much we can trust this library for a new release :sweat_smile: I think I'll politely ask the author.

EDIT: seems like this has been used by sccache.

**Comment by vrmiguel** [comment]
amazing PR 🥺

**Pull request merged**
