### PR TITLE
Generate completions and man page

### PR DESCRIPTION
**Pull request by figsoda**
Moved some parts of `cli.rs` to `opts.rs`, `ouch::cli::{Opts, QuestionPolicy, Subcommand}` are moved to `ouch::{Opts, QuestionPolicy, Subcommand}`

This uses a build script to generate completions when `GEN_COMPLETIONS=1` is present, this generates completions to `$OUT_DIR/completions`, for example:
- `GEN_COMPLETIONS=1 cargo build` would generate completions to `target/debug/build/ouch-*/out/completions`
- `GEN_COMPLETIONS=1 cargo build --release --target x86_64-unknown-linux-musl` would generate completions to `target/x86_64-unknown-linux-musl/release/build/ouch-*/out/completions`

A few more artifacts are generated in the completions in the `x86_64-musl` job:
- completions are generated and uploaded to `completions`
- man pages are generated with `help2man` and uploaded to `ouch.1`

Design choices:
- I chose completions to be generated to `OUT_DIR`, which is what rust/cargo recommends, but it also makes paths incredibly long and can possibly collide (when globbing with `*`) when completions are generated multiple times
- Man page could also be gzipped
- Completions could be in multiple artifacts, and powershell and zsh completions are named slightly intuitively since I left them as defaults

Side notes:
- I couldn't figure out a way for man pages to be generated inside `build.rs` since `help2man` excepts an executable, not a string
- The current ci is very big and repetitive, I have a very similar workflow that tests, builds, and creates releases on multiple platforms that we can probably borrow from: https://github.com/figsoda/mmtc/tree/main/.github/workflows

### CODE REVIEW

**Comment by figsoda** [comment]
resolved the merge conflicts

**Comment by marcospb19** [comment]
Nice PR!

> The current ci is very big and repetitive, I have a very similar workflow that tests, builds, and creates releases on multiple platforms that we can probably borrow from: https://github.com/figsoda/mmtc/tree/main/.github/workflows

Just saw your CI file and learned some stuff from it, seems like you can upload artifacts for each different job while keeping the different name for each of them, but can you optionally not upload the binaries for some of the jobs? (like we do currently).

> I chose completions to be generated to OUT_DIR, which is what rust/cargo recommends, but it also makes paths incredibly long and can possibly collide (when globbing with *) when completions are generated multiple times

The odds of this colliding is high?

> Man page could also be gzipped

Would be nice if you could gzip them CI before uploading, but I'm a noob when it comes to CI, is it easy to do? (@vrmiguel managed to learn github actions and did everything for `ouch`, I did practically nothing).

**Comment by figsoda** [comment]
> seems like you can upload artifacts for each different job while keeping the different name for each of them

Actually I don't upload any artifacts, the jobs only upload stuff to the releases

> but can you optionally not upload the binaries for some of the jobs?

Should be possible, the main difference is more uses of matrix

> The odds of this colliding is high?

If you run `cargo build` with `GEN_COMPLETIONS` multiple times, trying to find the completion directory with `*`s will find you multiple directories, and there is no easy way to find out which is the newest one. This shouldn't be a issue in ci, but might be a little annoying when testing changes to completions

> Would be nice if you could gzip them CI before uploading

I should've mentioned that artifacts are in `.zip` formats, should I still gzip it into `ouch.1.gz` and have it be stored in a zip?

**Comment by marcospb19** [comment]
> I should've mentioned that artifacts are in .zip formats, should I still gzip it into ouch.1.gz and have it be stored in a zip?

Oh yes, there's this, so no, leave them uncompressed, I'll probably need to create a script to help with releases anyway, so I could add this step to it.

**Comment by figsoda** [comment]
resolved merge conflicts

**Comment by marcospb19** [comment]
Resolved some more conflicts that appeared, thanks for the contribution and sorry for the delay!

**Comment by marcospb19** [comment]
@figsoda have you tried out the zsh completion? Bash is working here but zsh is not.

**Comment by figsoda** [comment]
I did not, I don't use zsh

Fish worked fine for me

**Comment by yigitsever** [comment]
zsh completion is not working because of the following in `_ouch` (line 40 on my install);

```
':output -- The resulting file. It's extensions can be used to specify the compression formats:_files' \
```

The `'` in `It's` is causing the problem, replacing the line as;
```
":output -- The resulting file. It's extensions can be used to specify the compression formats:_files" \
```
Fixes the issue, I don't know about the generation process so just fixed it by hand in the meantime.

**Comment by figsoda** [comment]
@yigitsever does this fix it for you?
https://github.com/ouch-org/ouch/pull/153

**Comment by yigitsever** [comment]
@figsoda it does, didn't even realize the typo...

**Pull request merged**
