### PR TITLE
fix: fix decompress issue with rar files which include CJK filenames in it

### PR DESCRIPTION
**Pull request by ttys3**
update unrar crate to [fix decompress issue with rar files which include CJK filenames in it](https://github.com/muja/unrar.rs/commit/5e6b83d91982234d3686b235dcbc7989402a88fd)

prev we fixed the CJK filename issue for the archive filename itself

this time, it is the filename in the archive.

that's to day, if `foo.rar` contains `❤️.txt`  in it, the decompression will fail

we need wait unrar crate to release a new version

### CODE REVIEW

**Comment by marcospb19** [comment]
Yeah, we need to wait for their release otherwise this can block a new version of Ouch.

**Comment by ttys3** [comment]
OK, I changed the PR to WIP status

**Review by marcospb19 — APPROVED** [review]
looks like you also updated all deps, I guess it's a good thing tho

**Comment by marcospb19** [comment]
ty, I see you created another PRs, sorry, I might take some time to take a proper look at them, busy week, but I'll catch up

**Pull request merged**
